---
- name: Update APT cache and install basic tools
  gather_facts: false
  hosts: ubuntu
  tasks:

  - name: Install deb package https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
    become: yes
    become_user: root
    apt:
      deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb

  - name: Update APT cache
    become: yes
    become_user: root
    apt:
      update_cache: yes

  - name: Install zabbix-agent
    become: yes
    become_user: root
    apt:
      name: zabbix-agent

  - name: Configure zabbix_agentd.conf
    become: yes
    become_user: root
    replace:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: 'Server=127.0.0.1'
      replace: 'Server=192.168.0.131'

  - name: Enable and restart zabbix-agent service
    become: yes
    become_user: root
    ansible.builtin.systemd:
      name: zabbix-agent.service
      enabled: yes
      state: restarted
