---
- name: Push SSH pubkeys to hosts
  gather_facts: false
  hosts: ubuntu
  tasks:

  - name: Adding data SSH key to authorized_keys
    authorized_key:
      user: sadmin
      state: present
      key: "{{ lookup('file', '/home/sadmin/keys/id_rsa_data.pub') }}"

  - name: Adding ansible SSH key to authorized_keys
    authorized_key:
      user: sadmin
      state: present
      key: "{{ lookup('file', '/home/sadmin/keys/id_rsa_ansible.pub') }}"
