---
- name: Set timezone to Budapest on Ubuntu hosts
  gather_facts: false
  hosts: ubuntus
  tasks:

    - name: Set timezone to Budapest on Ubuntu hosts
      community.general.timezone:
       name: Europe/Budapest
      become: yes
      become_method: sudo

